---
- name: Network Analytics and Reporting
  hosts: localhost
  tasks:
    - name: Measure latency
      shell: "ping -c 4 google.com | grep avg | awk -F'/' '{print $5}'"
      register: latency

    - name: Measure download speed
      shell: "curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python - | grep 'Download' | awk '{print $2}'"
      register: download_speed

    - name: Measure uptime
      shell: "awk '{print $1}' /proc/uptime"
      register: uptime

    - name: Generate report
      copy:
        dest: /tmp/network_report.txt
        content: |
          Network Analytics Report:
          =========================
          Latency: {{ latency.stdout }} ms
          Download Speed: {{ download_speed.stdout }} Mbps
          Uptime: {{ uptime.stdout }}

- name: Send email with the report
  community.general.mail:
    host: smtp-mail.outlook.com
    port: 587
    username: "youremail@outlook.com"
    password: "your_app_password"
    to:
      - "recipient@example.com"
    subject: "Daily Network Analytics Report"
    body: |
      Please find the attached network analytics report.
    attach:
      - /tmp/network_report.txt
    secure: starttls
    debug: true
