---
- name: Network Analytics and Reporting
  hosts: localhost
  tasks:
    - name: Install iputils (ping) if not already installed
      shell: |
        if ! command -v ping &> /dev/null; then
          yum install -y iputils || echo "Failed to install iputils";
        fi
      register: install_ping
      changed_when: false

    - name: Debug raw ping output
      shell: ping -c 4 google.com
      register: raw_ping
      changed_when: false
      ignore_errors: yes

    - name: Show raw ping output
      debug:
        var: raw_ping.stdout

    - name: Measure latency
      shell: >
        /usr/bin/ping -c 4 google.com |
        (grep 'rtt' || echo 'N/A') |
        awk -F'= ' '{print $2}' |
        awk -F'/' '{print $2}' |
        awk '{printf "%.2f", $1}'
      register: latency
      changed_when: false
      args:
        executable: /bin/bash

    - name: Debug latency output
      debug:
        var: latency.stdout

    - name: Measure download speed
      shell: >
        curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py |
        python3 - --secure |
        grep 'Download' |
        awk '{print $2}'
      register: download_speed
      ignore_errors: yes

    - name: Measure uptime
      shell: "awk '{print $1}' /proc/uptime"
      register: uptime

    - name: Generate report
      copy:
        dest: /tmp/network_report.txt
        content: |
          📊 Network Performance Report
          ───────────────────────────────
          🔁 Latency       │ {{ latency.stdout | default('N/A') }} ms
          📥 Download Speed │ {{ download_speed.stdout | default('N/A') }} Mbps
          ⏱️ Uptime        │ {{ uptime.stdout | float | default(0) / 3600 | round(2) }} hours
          ───────────────────────────────

    - name: Send email with report
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "equipmentold@gmail.com"
        password: "odng upwk lixm scqh"  # Replace with App Password
        to: "gjb1088@gmail.com"
        subject: "Daily Network Analytics Report"
        body: |
          Attached is the latest network performance report.
          
          📊 Key Metrics:
          - Latency: {{ latency.stdout | default('N/A') }} ms
          - Download Speed: {{ download_speed.stdout | default('N/A') }} Mbps
          - Uptime: {{ uptime.stdout | float | default(0) / 3600 | round(2) }} hours
        attach: /tmp/network_report.txt
        secure: starttls
        timeout: 30
