- name: Network Analytics and Reporting
  hosts: localhost
  tasks:
    - name: Measure latency
      shell: >
        ping -c 4 google.com | 
        awk -F'/' '/avg/{print $5}' | 
        awk '{print $1}'
      register: latency
      ignore_errors: yes

    - name: Measure download speed
      shell: >
        curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py |
        python3 - --secure |
        grep 'Download' |
        awk '{print $2}'
      register: download_speed
      ignore_errors: yes

    - name: Measure uptime
      shell: "awk '{print $1}' /proc/uptime"
      register: uptime

    - name: Generate report
      copy:
        dest: /tmp/network_report.txt
        content: |
          📊 Network Performance Report
          ───────────────────────────────
          🔁 Latency       │ {{ latency.stdout | default('N/A') }} ms
          📥 Download Speed │ {{ download_speed.stdout | default('N/A') }} Mbps
          ⏱️ Uptime        │ {{ uptime.stdout | float | default(0) / 3600 | round(2) }} hours
          ───────────────────────────────

    - name: Verify report file exists
      stat:
        path: /tmp/network_report.txt
      register: report_file

    - name: Fail if report missing
      fail:
        msg: "Report file not found at /tmp/network_report.txt"
      when: not report_file.stat.exists


    - name: Debug SMTP settings
      debug:
        msg: |
          Host: smtp.gmail.com
          Port: 587
          Username: equipmentold@gmail.com
          Password: "inpb nclm tcvo tudq"
          Secure: starttls

    - name: Send email with the report
      community.general.mail:
        host: smtp.gmail.com  # Corrected hostname
        port: 587
        username: "equipmentold@gmail.com"
        password: "inpb nclm tcvo tudq"  # Use App Password if 2FA is enabled
        to:
          - "gjb1088@gmail.com"
        subject: "Daily Network Analytics Report"
        body: |
          Attached is the latest network performance report.
          
          📊 Key Metrics:
          - Latency: {{ latency.stdout | default('N/A') }} ms
          - Download Speed: {{ download_speed.stdout | default('N/A') }} Mbps
          - Uptime: {{ uptime.stdout | float | default(0) / 3600 | round(2) }} hours
        attach:
          - /tmp/network_report.txt
        secure: starttls
        timeout: 30
