---
- name: Network Analytics and Reporting
  hosts: localhost
  tasks:
    - name: Measure latency
      shell: "ping -c 4 google.com | grep avg | awk -F'/' '{print $5}'"
      register: latency

    - name: Measure download speed
      shell: "curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 - | grep 'Download' | awk '{print $2}'"
      register: download_speed

    - name: Measure uptime
      shell: "awk '{print $1}' /proc/uptime"
      register: uptime

    - name: Generate report
      copy:
        dest: /tmp/network_report.txt
        content: |
          Network Analytics Report:
          ==========================
          Latency: {{ latency.stdout }} ms
          Download Speed: {{ download_speed.stdout }} Mbps
          Uptime: {{ uptime.stdout | float / 3600 | round(2) }} hours

    - name: Verify the report file exists
      stat:
        path: /tmp/network_report.txt
      register: report_file

    - name: Ensure the report file exists before sending email
      fail:
        msg: "The report file does not exist at /tmp/network_report.txt"
      when: not report_file.stat.exists

    - name: Send email with the report
      community.general.mail:
        host: smtp.gmail.org
        port: 587
        username: "equipmentold@gmail.com"
        password: "HelloThere1088!"
        to:
          - "gjb1088@gmail.com"
        subject: "Daily Network Analytics Report"
        body: |
          Please find the attached network analytics report.
        attach:
          - /tmp/network_report.txt
        secure: starttls
        timeout: 30
